server.port = 8081

page.size = 5

jwt.secret=RAYS
#jwt.expiration=3600000
jwt.expiration=36000

#Datasource
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/p10}

spring.datasource.username=root
spring.datasource.password=root

#Hibernate/JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true


#Hibernate dddl
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.dialect=org.hibernate.dialect.MariaDB53Dialect
spring.jpa.hibernate.current_session_context-class=org.springframework.orm.hibernate.SpringSessionContext

spring.datasource.hikari.connection-timeout=3000


#Email Server Parameters
smtp.server=smtp.gmail.com
smtp.port=465
email.login=rajputaniket121@gmail.com
email.pwd=noah divv uqvo nxle